
/*******1. DDL queries of Oracle_Demo_to_Snowflake environment under Snowflake_MG system   ********/

/***** Script Date: Thu May 20 16:46:49 IST 2021 ******/


/****** Object:  Table STG_DV.STG_CUSTOMER   *****/
create Or Replace TABLE STG_DV.STG_CUSTOMER (
    SQN_NUM INTEGER NOT NULL,
    CUSTOMER_HSH CHAR(6) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    NATION_HSH CHAR(32) NOT NULL,
    CUSTOMER_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(100) NOT NULL,
    C_CUSTKEY VARCHAR(100) NULL,
    C_NAME VARCHAR(100) NULL,
    C_ADDRESS VARCHAR(100) NULL,
    C_NATIONKEY VARCHAR(100) NULL,
    C_PHONE VARCHAR(100) NULL,
    C_ACCTBAL VARCHAR(100) NULL,
    C_MKTSEGMENT VARCHAR(100) NULL,
    C_COMMENT VARCHAR(100) NULL
    );

/****** Object:  Table STG_DV.STG_LINEITEM   *****/
create Or Replace TABLE STG_DV.STG_LINEITEM (
    SQN_NUM INTEGER NOT NULL,
    LINEITEM_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    ORDERS_HSH CHAR(32) NOT NULL,
    PART_HSH CHAR(32) NOT NULL,
    SUPPLIER_HSH CHAR(32) NOT NULL,
    LINEITEM_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    L_ORDERKEY VARCHAR(255) NULL,
    L_PARTKEY VARCHAR(255) NULL,
    L_SUPPKEY VARCHAR(255) NULL,
    L_LINENUMBER VARCHAR(255) NULL,
    L_QUANTITY VARCHAR(255) NULL,
    L_EXTENDEDPRICE VARCHAR(255) NULL,
    L_DISCOUNT VARCHAR(255) NULL,
    L_TAX VARCHAR(255) NULL,
    L_RETURNFLAG VARCHAR(255) NULL,
    L_LINESTATUS VARCHAR(255) NULL,
    L_SHIPDATE DATE NULL,
    L_COMMITDATE DATE NULL,
    L_RECEIPTDATE DATE NULL,
    L_SHIPINSTRUCT VARCHAR(255) NULL,
    L_SHIPMODE VARCHAR(255) NULL,
    L_COMMENT VARCHAR(255) NULL
    );

/****** Object:  Table STG_DV.STG_NATION   *****/
create Or Replace TABLE STG_DV.STG_NATION (
    SQN_NUM INTEGER NOT NULL,
    NATION_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    REGION_HSH CHAR(32) NOT NULL,
    NATION_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    N_NATIONKEY VARCHAR(255) NULL,
    N_NAME VARCHAR(255) NULL,
    N_REGIONKEY VARCHAR(255) NULL,
    N_COMMENT VARCHAR(255) NULL
    );

/****** Object:  Table STG_DV.STG_ORDERS   *****/
create Or Replace TABLE STG_DV.STG_ORDERS (
    SQN_NUM INTEGER NOT NULL,
    ORDERS_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    CUSTOMER_HSH CHAR(32) NOT NULL,
    ORDERS_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    O_ORDERKEY VARCHAR(255) NULL,
    O_CUSTKEY VARCHAR(255) NULL,
    O_ORDERSTATUS VARCHAR(255) NULL,
    O_TOTALPRICE VARCHAR(255) NULL,
    O_ORDERDATE VARCHAR(255) NULL,
    O_ORDERPRIORITY VARCHAR(255) NULL,
    O_CLERK VARCHAR(255) NULL,
    O_SHIPPRIORITY VARCHAR(255) NULL,
    O_COMMENT VARCHAR(255) NULL
    );

/****** Object:  Table STG_DV.STG_PART   *****/
create Or Replace TABLE STG_DV.STG_PART (
    SQN_NUM INTEGER NOT NULL,
    PART_HSH CHAR(32) NOT NULL,
    PART_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    P_PARTKEY VARCHAR(255) NULL,
    P_NAME VARCHAR(255) NULL,
    P_MFGR VARCHAR(255) NULL,
    P_BRAND VARCHAR(255) NULL,
    P_TYPE VARCHAR(255) NULL,
    P_SIZE VARCHAR(255) NULL,
    P_CONTAINER VARCHAR(255) NULL,
    P_RETAILPRICE VARCHAR(255) NULL,
    P_COMMENT VARCHAR(255) NULL
    );

/****** Object:  Table STG_DV.STG_PARTSUPP   *****/
create Or Replace TABLE STG_DV.STG_PARTSUPP (
    SQN_NUM INTEGER NOT NULL,
    PARTSUPP_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    PART_HSH CHAR(32) NOT NULL,
    SUPPLIER_HSH CHAR(32) NOT NULL,
    PARTSUPP_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    PS_PARTKEY VARCHAR(255) NULL,
    PS_SUPPKEY VARCHAR(255) NULL,
    PS_AVAILQTY VARCHAR(255) NULL,
    PS_SUPPLYCOST VARCHAR(255) NULL,
    PS_COMMENT VARCHAR(255) NULL
    );

/****** Object:  Table STG_DV.STG_REGION   *****/
create Or Replace TABLE STG_DV.STG_REGION (
    SQN_NUM INTEGER NOT NULL,
    REGION_HSH CHAR(32) NOT NULL,
    REGION_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    R_REGIONKEY VARCHAR(255) NULL,
    R_NAME VARCHAR(255) NULL,
    R_COMMENT VARCHAR(255) NULL
    );

/****** Object:  Table STG_DV.STG_SUPPLIER   *****/
create Or Replace TABLE STG_DV.STG_SUPPLIER (
    SQN_NUM INTEGER NOT NULL,
    SUPPLIER_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    NATION_HSH CHAR(32) NOT NULL,
    SUPPLIER_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATE NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    S_SUPPKEY VARCHAR(255) NULL,
    S_NAME VARCHAR(255) NULL,
    S_ADDRESS VARCHAR(255) NULL,
    S_NATIONKEY VARCHAR(255) NULL,
    S_PHONE VARCHAR(255) NULL,
    S_ACCTBAL VARCHAR(255) NULL,
    S_COMMENT VARCHAR(255) NULL
    );



