
/*******1. DDL queries of Snowfkale_STG environment under Snowflake system   ********/

/***** Script Date: Wed May 19 17:23:19 IST 2021 ******/


/****** Object:  Table STG_DV.STG_CUSTOMER   *****/
create Or Replace TABLE STG_DV.STG_CUSTOMER (
    SQN_NUM NUMERIC NOT NULL,
    CUSTOMER_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    NATION_HSH CHAR(32) NOT NULL,
    CUSTOMER_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    C_CUSTKEY  NULL,
    C_NAME  NULL,
    C_ADDRESS  NULL,
    C_NATIONKEY  NULL,
    C_PHONE  NULL,
    C_ACCTBAL  NULL,
    C_MKTSEGMENT  NULL,
    C_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_LINEITEM   *****/
create Or Replace TABLE STG_DV.STG_LINEITEM (
    SQN_NUM NUMERIC NOT NULL,
    LINEITEM_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    ORDERS_HSH CHAR(32) NOT NULL,
    PART_HSH CHAR(32) NOT NULL,
    SUPPLIER_HSH CHAR(32) NOT NULL,
    LINEITEM_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    L_ORDERKEY  NULL,
    L_PARTKEY  NULL,
    L_SUPPKEY  NULL,
    L_LINENUMBER  NULL,
    L_QUANTITY  NULL,
    L_EXTENDEDPRICE  NULL,
    L_DISCOUNT  NULL,
    L_TAX  NULL,
    L_RETURNFLAG  NULL,
    L_LINESTATUS  NULL,
    L_SHIPDATE  NULL,
    L_COMMITDATE  NULL,
    L_RECEIPTDATE  NULL,
    L_SHIPINSTRUCT  NULL,
    L_SHIPMODE  NULL,
    L_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_NATION   *****/
create Or Replace TABLE STG_DV.STG_NATION (
    SQN_NUM NUMERIC NOT NULL,
    NATION_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    REGION_HSH CHAR(32) NOT NULL,
    NATION_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    N_NATIONKEY  NULL,
    N_NAME  NULL,
    N_REGIONKEY  NULL,
    N_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_ORDERS   *****/
create Or Replace TABLE STG_DV.STG_ORDERS (
    SQN_NUM NUMERIC NOT NULL,
    ORDERS_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    CUSTOMER_HSH CHAR(32) NOT NULL,
    ORDERS_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    O_ORDERKEY  NULL,
    O_CUSTKEY  NULL,
    O_ORDERSTATUS  NULL,
    O_TOTALPRICE  NULL,
    O_ORDERDATE  NULL,
    O_ORDERPRIORITY  NULL,
    O_CLERK  NULL,
    O_SHIPPRIORITY  NULL,
    O_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_PART   *****/
create Or Replace TABLE STG_DV.STG_PART (
    SQN_NUM NUMERIC NOT NULL,
    PART_HSH CHAR(32) NOT NULL,
    PART_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    P_PARTKEY  NULL,
    P_NAME  NULL,
    P_MFGR  NULL,
    P_BRAND  NULL,
    P_TYPE  NULL,
    P_SIZE  NULL,
    P_CONTAINER  NULL,
    P_RETAILPRICE  NULL,
    P_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_PARTSUPP   *****/
create Or Replace TABLE STG_DV.STG_PARTSUPP (
    SQN_NUM NUMERIC NOT NULL,
    PARTSUPP_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    PART_HSH CHAR(32) NOT NULL,
    SUPPLIER_HSH CHAR(32) NOT NULL,
    PARTSUPP_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    PS_PARTKEY  NULL,
    PS_SUPPKEY  NULL,
    PS_AVAILQTY  NULL,
    PS_SUPPLYCOST  NULL,
    PS_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_REGION   *****/
create Or Replace TABLE STG_DV.STG_REGION (
    SQN_NUM NUMERIC NOT NULL,
    REGION_HSH CHAR(32) NOT NULL,
    REGION_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    R_REGIONKEY  NULL,
    R_NAME  NULL,
    R_COMMENT  NULL,
    primary key (SQN_NUM)
    );

/****** Object:  Table STG_DV.STG_SUPPLIER   *****/
create Or Replace TABLE STG_DV.STG_SUPPLIER (
    SQN_NUM NUMERIC NOT NULL,
    SUPPLIER_HSH CHAR(32) NOT NULL,
    LNK_HSH CHAR(32) NOT NULL,
    NATION_HSH CHAR(32) NOT NULL,
    SUPPLIER_HSH_DIFF CHAR(32) NOT NULL,
    LOAD_DTS DATETIME NOT NULL,
    REC_SRC VARCHAR(255) NOT NULL,
    S_SUPPKEY  NULL,
    S_NAME  NULL,
    S_ADDRESS  NULL,
    S_NATIONKEY  NULL,
    S_PHONE  NULL,
    S_ACCTBAL  NULL,
    S_COMMENT  NULL,
    primary key (SQN_NUM)
    );



